version: 2

models:
  - name: dm_shop_detail
    description: "demo model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
