version: 2

models:
  - name: dm_shop_detail
    description: "demo model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

models:
  - name: dm_people_adujst
    description: "demo model"


models:
  - name: '区域经理业绩'
    description: "demo model"


models:
  - name: '产品类别环比'
    description: "demo model"
